### ISSUE TITLE
run eror

### ISSUE THREAD

**Issue by nvquangil** [flaming-chameleon/telegram-blum-auto#27]
D:\Python\telegram-blum-auto-main>python main.py
Traceback (most recent call last):
  File "D:\Python\telegram-blum-auto-main\main.py", line 1, in <module>
    from utils.core import create_sessions, logger
  File "D:\Python\telegram-blum-auto-main\utils\core\__init__.py", line 2, in <module>
    from .register import create_sessions
  File "D:\Python\telegram-blum-auto-main\utils\core\register.py", line 4, in <module>
    from data import config
  File "D:\Python\telegram-blum-auto-main\data\config.py", line 3
    API_HASH = 6dc8ac60680a7af7bc8803a76c37c728
               ^
SyntaxError: invalid decimal literal

D:\Python\telegram-blum-auto-main>

i use python 3.10

**Comment by gmixaOI** [comment]
> API_HASH = 6dc8ac60680a7af7bc8803a76c37c728
use this line(line must be string)
API_HASH = '6dc8ac60680a7af7bc8803a76c37c728'
